<?php


/**
 * Implements hook_menu().
 */
function json_generator_menu() {
  $items = array();

  // Tell Drupal to generate a form for 'admin/config/json_generator' URL.
  // The form is defined in 'json_generator_admin_settings' function.
  // The URL should be accessible only by those with
  // 'administer site configuration' permission.
  $items['admin/config/json_generator'] = array(
    'title' => "JSON Generator Form",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('json_generator_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}


/**
 * Implements hook_form().
 */
function json_generator_admin_settings($form, &$form_state) {
  $form = array();

  // Create a 'json_generator' form labeled as 'Custom Text'
  // containing a text area for inputting custom texts.
  // It has 5 rows and every time you reload that page the value
  // should be set to the previously entered one,
  $form['json_generator'] = array(
    '#type' => 'textarea',
    '#title' => t('Custom Text'),
    '#rows' => 5,
    '#default_value' => variable_get('json_generator'),
  );

  // Create a system-generated submit form. This is equivalent to:
  // $form['#submit'][] = 'system_settings_form_submit';
  // The advantage of this 'submit' callback is the automatic execution of
  // variable_set('json_generator') and auto-display of message
  // after saving the form.
  $form = system_settings_form($form);

  return $form;
}
